[norg-specs-main]
git-tree-sha1 = "72da8eeefd68fb48f1c0ffd51fdbbeae0cd09efe"

    [[norg-specs-main.download]]
    sha256 = "088c7c200f47bd883c3bee46369d675ff0b817f7b02ba0df384d565d8d25dfa2"
    url = "https://github.com/nvim-neorg/norg-specs/tarball/1.0"
