name = "Norg"
uuid = "64228516-68de-4e23-8112-6940bc1970d1"
authors = ["Hugo Levy-Falk <hugo@klafyvel.me> and contributors"]
version = "0.3.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[extensions]
TimeZonesExt = "TimeZones"

[compat]
AbstractTrees = "0.4"
OrderedCollections = "1"
SnoopPrecompile = "1"
HypertextLiteral = "0.9"
TimeZones = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
